add breadcrumbs navigation so the user knows where they are
sul-cidr/histonets pull request #174
Opened 2017-06-22 01:25 UTC by aeschylus

2017-06-22 01:26 UTC, aeschylus commented
Need to write some tests as well.

2017-06-28 19:06 UTC, mejackreed requested changes
Looks great! Great job on the style of all of this. I really like how you implemented the links and the arrow breadcrumbs.

Would mind doing the following?

 - squashing down the changes into a single commit (perhaps the gem version changes could be in a separate commit)
 - removing (or separating into another commit) the `yarn.lock` changes?

2017-06-30 13:07 UTC, mejackreed commented
I'm also getting some kind of strange overlap here

![screen shot 2017-06-30 at 9 07 04 am](https://user-images.githubusercontent.com/1656824/27736752-8dee4912-5d73-11e7-8326-8a0890168536.png)

2017-06-30 16:41 UTC, mejackreed approved these changes

2017-06-30 16:54 UTC, merged